# Random Intro

### Generating random integer and float number

In [ ]:
import numpy as np
from numpy import random
xint = random.randint(100) 
#will pick a random integer between 1 and 100
print(xint)

xfloat = random.rand() 
#will pick a random float between 0 and 1
print(xfloat)

### Generating random array

In [ ]:
x = random.randint(100, size=(5)) 
#will generate an array of five random numbers between 1 and 100
print(x)

x = random.rand(10, 10) 
#will generate a 2d array of ten random numbers between 100 and 200
print(x)

### Pick random no. from an array

In [ ]:
x = random.choice([3, 5, 2, 8, 1, 65]) 
#The choice command will pick a random no. from the arrya and store it in the varoable x
print(x)

x = random.choice([3, 5, 2, 8, 1, 65], size=(2, 10)) 
#The choice command will pick a random no. from the arryay and store it in the varoable x
#The size parameter will help in generating an array of a specific no. of rows and columns consisting of random no. given i the array
print(x)

# Data distribution

### Data distribution

In [ ]:
x = random.choice([1, 3, 5, 6], p=[0.1, 0.4, 0.3, 0.2], size=(100)) 
#will create an array of 100 elemets consisting of elements entered in the array
#"p" define the probablity of occurance of each of the element
#size defines the no. of rows and columns
print(x)

arr = random.choice([1, 3, 5, 2, 6], p=[0.1, 0.0, 0.5, 0.3, 0.1], size=(2, 50))
print(arr) 
#even if this array is prited 100 times all the values willl be different but 3 will never occur

### Random permutation

In [28]:
arr=np.array([2, 4, 6, 3, 6])
random.shuffle(arr)
#will shuffle the positions of the elemets in the array randomly everytime the code is ran
print(arr)
#random.shuffle() makes changes to the org. array

newarr = np.array([4, 3, 6, 2, 9])
print(random.permutation(newarr))
print(newarr)
#random.permutation() will shuffle the elements but will not change the original array
#hence the output of print(newarr) is always the same

[6 3 2 6 4]
[4 6 9 2 3]
[4 3 6 2 9]


### random.shuffle() vs random.permuatation()

* random.shuffle() changes the original array
* random.permutation() just makes a view of the arrya and shuffles the elements of that 